            import 'package:flutter/material.dart';
            import 'package:firebase_auth/firebase_auth.dart';
            import 'signup_screen.dart';

            class LoginScreen extends StatefulWidget {
              const LoginScreen({super.key});

                @override
                  State<LoginScreen> createState() => _LoginScreenState();
                  }

                  class _LoginScreenState extends State<LoginScreen> {
                    final _emailController = TextEditingController();
                      final _passwordController = TextEditingController();
                        final _auth = FirebaseAuth.instance;
                          bool _isLoading = false;
                            String _errorMessage = '';

                              Future<void> _login() async {
                                  setState(() {
                                        _isLoading = true;
                                              _errorMessage = '';
                                                  });

                                                      try {
                                                            await _auth.signInWithEmailAndPassword(
                                                                    email: _emailController.text.trim(),
                                                                            password: _passwordController.text.trim(),
                                                                                  );

                                                                                        if (!mounted) return;

                                                                                              // الانتقال إلى الصفحة الرئيسية بعد تسجيل الدخول بنجاح
                                                                                                    // يمكنك استبدال Scaffold المؤقت أدناه بالصفحة الرئيسية الفعلية لتطبيقك (مثل MerchantsPage)
                                                                                                          Navigator.pushReplacement(
                                                                                                                  context,
                                                                                                                          MaterialPageRoute(
                                                                                                                                    builder: (context) => const Scaffold(
                                                                                                                                                body: Center(
                                                                                                                                                              child: Text(
                                                                                                                                                                              'تم تسجيل الدخول بنجاح!',
                                                                                                                                                                                              style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                                                                                                                                                                                                            ),
                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                    } on FirebaseAuthException catch (e) {
                                                                                                                                                                                                                                                          setState(() {
                                                                                                                                                                                                                                                                  _errorMessage = e.message ?? 'حدث خطأ أثناء تسجيل الدخول';
                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                            } finally {
                                                                                                                                                                                                                                                                                  setState(() {
                                                                                                                                                                                                                                                                                          _isLoading = false;
                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                        @override
                                                                                                                                                                                                                                                                                                          void dispose() {
                                                                                                                                                                                                                                                                                                              _emailController.dispose();
                                                                                                                                                                                                                                                                                                                  _passwordController.dispose();
                                                                                                                                                                                                                                                                                                                      super.dispose();
                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                          @override
                                                                                                                                                                                                                                                                                                                            Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                return Scaffold(
                                                                                                                                                                                                                                                                                                                                      appBar: AppBar(
                                                                                                                                                                                                                                                                                                                                              title: const Text('تسجيل الدخول'),
                                                                                                                                                                                                                                                                                                                                                      centerTitle: true,
                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                  body: Padding(
                                                                                                                                                                                                                                                                                                                                                                          padding: const EdgeInsets.all(16.0),
                                                                                                                                                                                                                                                                                                                                                                                  child: Column(
                                                                                                                                                                                                                                                                                                                                                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                                                                                                                                                                                                                                                                                                                                                                      children: [
                                                                                                                                                                                                                                                                                                                                                                                                                  TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                controller: _emailController,
                                                                                                                                                                                                                                                                                                                                                                                                                                              decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                              labelText: 'البريد الإلكتروني',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              border: OutlineInputBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          keyboardType: TextInputType.emailAddress,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            controller: _passwordController,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          labelText: 'كلمة المرور',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: OutlineInputBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      obscureText: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (_errorMessage.isNotEmpty)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        _errorMessage,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style: const TextStyle(color: Colors.red),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              _isLoading
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? const CircularProgressIndicator()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              : SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width: double.infinity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      height: 50,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onPressed: _login,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      child: const Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'دخول',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style: TextStyle(fontSize: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          TextButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onPressed: () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Navigator.push(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          context,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            MaterialPageRoute(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                builder: (context) => const SignupScreen(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child: const Text('ليس لديك حساب؟ انقر هنا لإنشاء حساب جديد'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                