import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';

class LoginScreen extends StatefulWidget {
  const LoginScreen({super.key});

    @override
      State<LoginScreen> createState() => _LoginScreenState();
      }

      class _LoginScreenState extends State<LoginScreen> {
        final _emailController = TextEditingController();
          final _passwordController = TextEditingController();
            final _auth = FirebaseAuth.instance;
              bool _isLoading = false;
                String _errorMessage = '';

                  Future<void> _login() async {
                      setState(() {
                            _isLoading = true;
                                  _errorMessage = '';
                                      });

                                          try {
                                                await _auth.signInWithEmailAndPassword(
                                                        email: _emailController.text.trim(),
                                                                password: _passwordController.text.trim(),
                                                                      );
                                                                            // في حال نجاح تسجيل الدخول، يمكنك الانتقال للشاشة الرئيسية للتطبيق
                                                                                  if (!mounted) return;
                                                                                        ScaffoldMessenger.of(context).showSnackBar(
                                                                                                const SnackBar(content: Text('تم تسجيل الدخول بنجاح!')),
                                                                                                      );
                                                                                                          } on FirebaseAuthException catch (e) {
                                                                                                                setState(() {
                                                                                                                        _errorMessage = e.message ?? 'حدث خطأ أثناء تسجيل الدخول';
                                                                                                                              });
                                                                                                                                  } finally {
                                                                                                                                        setState(() {
                                                                                                                                                _isLoading = false;
                                                                                                                                                      });
                                                                                                                                                          }
                                                                                                                                                            }

                                                                                                                                                              @override
                                                                                                                                                                Widget build(BuildContext context) {
                                                                                                                                                                    return Scaffold(
                                                                                                                                                                          appBar: AppBar(
                                                                                                                                                                                  title: const Text('تسجيل الدخول'),
                                                                                                                                                                                        ),
                                                                                                                                                                                              body: Padding(
                                                                                                                                                                                                      padding: const EdgeInsets.all(16.0),
                                                                                                                                                                                                              child: Column(
                                                                                                                                                                                                                        mainAxisAlignment: MainAxisAlignment.center,
                                                                                                                                                                                                                                  children: [
                                                                                                                                                                                                                                              TextField(
                                                                                                                                                                                                                                                            controller: _emailController,
                                                                                                                                                                                                                                                                          decoration: const InputDecoration(labelText: 'البريد الإلكتروني'),
                                                                                                                                                                                                                                                                                        keyboardType: TextInputType.emailAddress,
                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                const SizedBox(height: 12),
                                                                                                                                                                                                                                                                                                                            TextField(
                                                                                                                                                                                                                                                                                                                                          controller: _passwordController,
                                                                                                                                                                                                                                                                                                                                                        decoration: const InputDecoration(labelText: 'كلمة المرور'),
                                                                                                                                                                                                                                                                                                                                                                      obscureText: true,
                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                                                                          if (_errorMessage.isNotEmpty)
                                                                                                                                                                                                                                                                                                                                                                                                                        Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                        _errorMessage,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        style: const TextStyle(color: Colors.red),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              _isLoading
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? const CircularProgressIndicator()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              : ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onPressed: _login,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      child: const Text('دخول'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      