import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';

class SignupScreen extends StatefulWidget {
  const SignupScreen({super.key});

    @override
      State<SignupScreen> createState() => _SignupScreenState();
      }

      class _SignupScreenState extends State<SignupScreen> {
        final _emailController = TextEditingController();
          final _passwordController = TextEditingController();
            final _auth = FirebaseAuth.instance;
              bool _isLoading = false;
                String _errorMessage = '';

                  Future<void> _signUp() async {
                      setState(() {
                            _isLoading = true;
                                  _errorMessage = '';
                                      });

                                          try {
                                                await _auth.createUserWithEmailAndPassword(
                                                        email: _emailController.text.trim(),
                                                                password: _passwordController.text.trim(),
                                                                      );
                                                                            
                                                                                  if (!mounted) return;
                                                                                        ScaffoldMessenger.of(context).showSnackBar(
                                                                                                const SnackBar(content: Text('تم إنشاء الحساب بنجاح!')),
                                                                                                      );
                                                                                                            Navigator.pop(context); // العودة لشاشة تسجيل الدخول بعد النجاح
                                                                                                                } on FirebaseAuthException catch (e) {
                                                                                                                      setState(() {
                                                                                                                              _errorMessage = e.message ?? 'حدث خطأ أثناء إنشاء الحساب';
                                                                                                                                    });
                                                                                                                                        } finally {
                                                                                                                                              setState(() {
                                                                                                                                                      _isLoading = false;
                                                                                                                                                            });
                                                                                                                                                                }
                                                                                                                                                                  }

                                                                                                                                                                    @override
                                                                                                                                                                      Widget build(BuildContext context) {
                                                                                                                                                                          return Scaffold(
                                                                                                                                                                                appBar: AppBar(
                                                                                                                                                                                        title: const Text('إنشاء حساب جديد'),
                                                                                                                                                                                              ),
                                                                                                                                                                                                    body: Padding(
                                                                                                                                                                                                            padding: const EdgeInsets.all(16.0),
                                                                                                                                                                                                                    child: Column(
                                                                                                                                                                                                                              mainAxisAlignment: MainAxisAlignment.center,
                                                                                                                                                                                                                                        children: [
                                                                                                                                                                                                                                                    TextField(
                                                                                                                                                                                                                                                                  controller: _emailController,
                                                                                                                                                                                                                                                                                decoration: const InputDecoration(labelText: 'البريد الإلكتروني'),
                                                                                                                                                                                                                                                                                              keyboardType: TextInputType.emailAddress,
                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                      const SizedBox(height: 12),
                                                                                                                                                                                                                                                                                                                                  TextField(
                                                                                                                                                                                                                                                                                                                                                controller: _passwordController,
                                                                                                                                                                                                                                                                                                                                                              decoration: const InputDecoration(labelText: 'كلمة المرور'),
                                                                                                                                                                                                                                                                                                                                                                            obscureText: true,
                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                    const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                                                                                if (_errorMessage.isNotEmpty)
                                                                                                                                                                                                                                                                                                                                                                                                                              Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                              _errorMessage,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              style: const TextStyle(color: Colors.red),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _isLoading
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ? const CircularProgressIndicator()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onPressed: _signUp,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: const Text('تسجيل حساب'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            