import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ?? AppLocalizations(const Locale('ar'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'dashboard_title': 'لوحة تحكم المنصة',
      'system_name': 'نظام إدارة التوصيل',
      'home': 'الرئيسية',
      'merchants': 'المتاجر والتجار',
      'drivers': 'السائقين',
      'orders': 'الطلبات',
      'customers': 'العملاء',
      'total_orders': 'إجمالي الطلبات',
      'active_merchants': 'المتاجر النشطة',
      'available_drivers': 'السائقين المتاحين',
      'total_sales': 'إجمالي المبيعات',
      'switch_lang': 'English',
      'select_role': 'اختر نوع الحساب',
      'choose_role_subtitle': 'قم باختيار نوع الحساب للمتابعة في التطبيق',
      'role_customer': 'عميل',
      'role_customer_desc': 'تصفح المتاجر واطلب الوجبات والمنتجات بسهولة',
      'role_merchant': 'متجر / تاجر',
      'role_merchant_desc': 'إدارة منتجاتك، استقبال الطلبات ومتابعة المبيعات',
      'role_driver': 'سائق توصيل',
      'role_driver_desc': 'استلام طلبات التوصيل، تتبع الخريطة وتحصيل الأرباح',
      'role_admin': 'مسؤول النظام (Admin)',
      'role_admin_desc': 'إدارة المنصة بالكامل، التجار، السائقين والإحصائيات',
      'login_title': 'تسجيل الدخول',
      'welcome_back': 'مرحباً بك مجدداً',
      'login_subtitle': 'الرجاء إدخال بيانات الحساب للمتابعة',
      'email_or_phone': 'البريد الإلكتروني أو رقم الهاتف',
      'password': 'كلمة المرور',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'sign_in': 'تسجيل الدخول',
      'dont_have_account': 'ليس لديك حساب؟',
      'create_account': 'إنشاء حساب جديد',
      'deliver_to': 'التوصيل إلى',
      'search_hint': 'ابحث عن متجر، وجبة، أو منتج...',
      'today_offers': 'عروض اليوم',
      'banner_discount': 'خصم يصل إلى 30%\nعلى الطلب الأول',
      'featured_stores': 'المتاجر المميزة',
      'popular_products': 'المنتجات الأكثر طلباً',
      'see_all': 'عرض الكل',
      'currency': 'ج.س',
      'delivery_fee': 'التوصيل: ',
      'all': 'الكل',
      'restaurants': 'مطاعم',
      'supermarkets': 'سوبرماركت',
      'pharmacies': 'صيدليات',
      'electronics': 'إلكترونيات',
      'nav_home': 'الرئيسية',
      'nav_explore': 'استكشف',
      'nav_orders': 'طلباتي',
      'nav_profile': 'حسابي',
      'product_details': 'تفاصيل المنتج',
      'description': 'وصف المنتج',
      'add_to_cart': 'إضافة إلى السلة',
      'cart_title': 'سلة التسوق',
      'empty_cart': 'السلة فارغة حالياً',
      'start_shopping': 'ابدأ التسوق الآن',
      'order_summary': 'ملخص الطلب',
      'subtotal': 'المجموع الفرعي',
      'delivery_fee_label': 'رسوم التوصيل',
      'total_amount': 'المبلغ الإجمالي',
      'proceed_checkout': 'المتابعة لتأكيد الطلب',
      'item_added': 'تمت إضافة المنتج إلى السلة بنجاح',
      'quantity': 'الكمية',
      'notes': 'ملاحظات خاصة (اختياري)',
      'merchant_dashboard': 'لوحة التاجر',
      'store_status': 'حالة المتجر',
      'store_open': 'مفتوح لاستقبال الطلبات',
      'store_closed': 'مغلق حالياً',
      'today_orders_count': 'طلبات اليوم',
      'today_sales': 'مبيعات اليوم',
      'products_management': 'إدارة المنتجات',
      'add_new_product': 'إضافة منتج جديد',
      'edit_product': 'تعديل المنتج',
      'product_name_label': 'اسم المنتج',
      'product_price_label': 'السعر (ج.س)',
      'available_status': 'متوفر',
      'out_of_stock_status': 'غير متوفر',
      'incoming_orders': 'الطلبات المستلمة',
      'order_details': 'تفاصيل الطلب',
      'accept': 'قبول الطلب',
      'reject': 'رفض الطلب',
      'start_preparing': 'بدء التحضير',
      'ready_for_pickup': 'جاهز للتسليم للسائق',
      'order_status_new': 'جديد',
      'order_status_preparing': 'قيد التحضير',
      'order_status_ready': 'جاهز للسائق',
      'order_status_completed': 'مكتمل',
      'order_status_canceled': 'ملغى',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'category': 'التصنيف',
      'driver_dashboard': 'تطبيق السائق',
      'online_status': 'متصل (جاهز لتلقي الطلبات)',
      'offline_status': 'غير متصل (أوفلاين)',
      'today_earnings': 'أرباح اليوم',
      'completed_trips': 'الرحلات المكتملة',
      'available_orders': 'الطلبات المتاحة القريبة',
      'active_trip': 'الرحلة الحالية',
      'pickup_from': 'الاستلام من',
      'deliver_to_customer': 'التوصيل إلى العميل',
      'payout': 'أجرة التوصيل',
      'distance': 'المسافة',
      'accept_job': 'قبول وتوصيل الطلب',
      'arrived_at_store': 'وصلت للمتجر',
      'picked_up': 'تم استلام الطلب',
      'arrived_at_customer': 'وصلت لموقع العميل',
      'complete_delivery': 'تم التسليم وتسليم المبلغ',
      'cancel_trip': 'إلغاء الرحلة',
      'map_preview': 'خريطة تتبع المسار والملاحة',
      'call_customer': 'اتصال بالعميل',
      'call_store': 'اتصال بالمتجر',
      'no_available_orders': 'لا توجد طلبات توصيل قريبة حالياً',
    },
    'en': {
      'dashboard_title': 'Platform Dashboard',
      'system_name': 'Delivery Management System',
      'home': 'Home',
      'merchants': 'Merchants & Stores',
      'drivers': 'Drivers',
      'orders': 'Orders',
      'customers': 'Customers',
      'total_orders': 'Total Orders',
      'active_merchants': 'Active Merchants',
      'available_drivers': 'Available Drivers',
      'total_sales': 'Total Sales',
      'switch_lang': 'العربية',
      'select_role': 'Select Account Type',
      'choose_role_subtitle': 'Choose your account type to proceed',
      'role_customer': 'Customer',
      'role_customer_desc': 'Browse stores, order food and products easily',
      'role_merchant': 'Merchant / Store',
      'role_merchant_desc': 'Manage products, receive orders, track sales',
      'role_driver': 'Delivery Driver',
      'role_driver_desc': 'Accept delivery jobs, track routes, earn income',
      'role_admin': 'System Admin',
      'role_admin_desc': 'Full platform management, merchants, drivers & analytics',
      'login_title': 'Sign In',
      'welcome_back': 'Welcome Back',
      'login_subtitle': 'Please enter your credentials to continue',
      'email_or_phone': 'Email or Phone Number',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'sign_in': 'Sign In',
      'dont_have_account': "Don't have an account?",
      'create_account': 'Create New Account',
      'deliver_to': 'Deliver to',
      'search_hint': 'Search store, food, or product...',
      'today_offers': 'Today Offers',
      'banner_discount': 'Up to 30% OFF\non your first order',
      'featured_stores': 'Featured Stores',
      'popular_products': 'Popular Products',
      'see_all': 'See All',
      'currency': 'SDG',
      'delivery_fee': 'Delivery: ',
      'all': 'All',
      'restaurants': 'Restaurants',
      'supermarkets': 'Supermarket',
      'pharmacies': 'Pharmacies',
      'electronics': 'Electronics',
      'nav_home': 'Home',
      'nav_explore': 'Explore',
      'nav_orders': 'My Orders',
      'nav_profile': 'Profile',
      'product_details': 'Product Details',
      'description': 'Description',
      'add_to_cart': 'Add to Cart',
      'cart_title': 'Shopping Cart',
      'empty_cart': 'Your cart is empty',
      'start_shopping': 'Start Shopping',
      'order_summary': 'Order Summary',
      'subtotal': 'Subtotal',
      'delivery_fee_label': 'Delivery Fee',
      'total_amount': 'Grand Total',
      'proceed_checkout': 'Proceed to Checkout',
      'item_added': 'Item added to cart successfully',
      'quantity': 'Quantity',
      'notes': 'Special Notes (Optional)',
      'merchant_dashboard': 'Merchant Dashboard',
      'store_status': 'Store Status',
      'store_open': 'Open for Orders',
      'store_closed': 'Currently Closed',
      'today_orders_count': "Today's Orders",
      'today_sales': "Today's Sales",
      'products_management': 'Products Management',
      'add_new_product': 'Add New Product',
      'edit_product': 'Edit Product',
      'product_name_label': 'Product Name',
      'product_price_label': 'Price (SDG)',
      'available_status': 'In Stock',
      'out_of_stock_status': 'Out of Stock',
      'incoming_orders': 'Incoming Orders',
      'order_details': 'Order Details',
      'accept': 'Accept Order',
      'reject': 'Reject Order',
      'start_preparing': 'Start Preparing',
      'ready_for_pickup': 'Ready for Driver',
      'order_status_new': 'New',
      'order_status_preparing': 'Preparing',
      'order_status_ready': 'Ready for Driver',
      'order_status_completed': 'Completed',
      'order_status_canceled': 'Canceled',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'category': 'Category',
      'driver_dashboard': 'Driver App',
      'online_status': 'Online (Ready)',
      'offline_status': 'Offline',
      'today_earnings': "Today's Earnings",
      'completed_trips': 'Completed Trips',
      'available_orders': 'Available Nearby Orders',
      'active_trip': 'Active Delivery',
      'pickup_from': 'Pickup from',
      'deliver_to_customer': 'Deliver to Customer',
      'payout': 'Delivery Fee',
      'distance': 'Distance',
      'accept_job': 'Accept Delivery',
      'arrived_at_store': 'Arrived at Store',
      'picked_up': 'Order Picked Up',
      'arrived_at_customer': 'Arrived at Customer',
      'complete_delivery': 'Complete Delivery',
      'cancel_trip': 'Cancel Delivery',
      'map_preview': 'Map Navigation Preview',
      'call_customer': 'Call Customer',
      'call_store': 'Call Store',
      'no_available_orders': 'No available orders nearby',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['ar', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
