name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-22.04
    steps:
      - name: Force remove gitmodules tracking
        run: |
          git config --remove-section submodule.flutter || true
          rm -rf .gitmodules || true
          git rm -f .gitmodules || true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: false
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build APK Release
        run: flutter build apk --release
        
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
